#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'git'
cookbook 'mysql'
cookbook 'python'
cookbook 'nginx'
cookbook 'php'
cookbook 'php-fpm'
cookbook 'varnish'
cookbook 'zsh'
